# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

pod 'SkyFloatingLabelTextField', '~> 3.0'

target 'Templates&Localizables' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Templates&Localizables

  target 'Templates&LocalizablesTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Templates&LocalizablesUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
