# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

pod 'SkyFloatingLabelTextField', '~> 3.0'

target 'proyect' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for proyect

  target 'proyectTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'proyectUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
